spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: ${GROQ_CHAT_MODEL:llama-3.2-90b-vision-preview}

dev:
  to:
    api-key: ${DEV_TO_API_KEY}
    base-url: ${DEV_TO_BASE_URL:https://dev.to}